KyleAMathews/react-headroom

src/index.cjsx
In React 0.13, your console will be littered with warnings (example: Warning: Unsupported vendor-prefixed style property webkitTransform. Did you mean WebkitTransform?). This PR removes all the warnings.
=> Uppercased prefixes to avoid console log warnings in React 0.13

package.json, src/index.cjsx
usefull for https://github.com/seatgeek/react-infinite/
related to https://github.com/seatgeek/react-infinite/pull/47
=> allow scrolling props.parent instead of on window only

examples/examples.cjsx, src/index.cjsx, src/shouldUpdate.coffee, test/calc.coffee
I've added a new prop called `pinStart`.When set, Headroom doesn't start pinning until you scroll the first `pinStart` pixels of the page. It can be used when you have another element above Headroom component.
You can test it in the examples page making these changes:
```
@@ -5,10 +5,12 @@ Headroom = require '../src/index'
module.exports = React.createClass
render: ->
<div style={{marginBottom: 64}}>
+      <div style={{height: '60px'}}>header</div>
<Headroom
onPin={-> console.log "pinned"}
onUnpin={-> console.log "unpinned"}
wrapperStyle={marginBottom: '3rem'}
+        pinStart=60
style={{
```
=> Add pinStart prop

package.json, src/index.cjsx
For what I understand with React 15.0 the core team removed their internal polyfill of `Object.assign` for an updated one ([here's the issue](https://github.com/facebook/react/pull/6376)).
This PR should make react-headroom compatibile with React 15.0.
=> Use object-assign instead of deprecated React's polyfill

package.json
I have a project that isn't able to upgrade to React 15 yet. Headroom functions with v0.14, but it's impossible to `npm shrinkwrap`.
```
npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: react@^15.0.2, required by react-addons-pure-render-mixin@15.0.2
```
=> Relax react-addons-pure-render-mixin requirement

src/index.js
This causes the initial class name to be correctly set to `headroom--unfixed`.
Its needed mainly for when  `pinStart` is greater than 0.
fixes #45
=> Change initial state class to 'headroom headroom--unfixed'

.babelrc, package.json, src/index.js, website/pages/index.md
The current version of the component unfortunately doesn't provide a full coverage for only using the CSS names instead of inline styles. So far the [deferred attachment of the transition after the initial scroll](https://github.com/KyleAMathews/react-headroom/blob/master/src/index.js#L172) is missing. With this update the `headroom--scrolled` classname is added and referenced in the docs.
In addition I've added the missing `eslint-plugin` for the react rules and included a `babel-plugin` which transforms `undefined` into `void` as its often easier to understand for other developers.
=> add classname for transition state

www/pages/index.md
I need this callback to show a `box-shadow` when pinned, but remove it when `scrollTop` is `0` like on [Medium.com](https://medium.com/@Oolong/2016-was-bad-enough-is-it-only-going-to-get-worse-3a33393e2211#.ej6jjqw0e). I went to hack this library and saw exactly what I needed hiding in the source.
=> Document `onUnfix`

src/shouldUpdate.js
Fix a race condition where we disabled Headroom at a certain scroll point (via our app).
unFix() would be called, and the scroll listener detached, but it was called one last time, and it would compute an 'unpin' action, which would hide the navbar (exactly the opposite of what we wanted).
=> Fix race condition when disabling

package.json, src/index.js
This change introduces the new method for accessing PropTypes. As of React 15.5, React.PropTypes is deprecated and has been extracted into a separate package (`prop-types`).
=> Add prop-types package; remove deprecated reference to React.PropTypes (v15.5)

src/index.js
Hi, thanks for the package, it works great, but I have a minor issue. When trying to use the fix advised in #36 to use react-headroom for a footer, I need to overwrite the `.headroom` classNames. However, I use a CSS in JS lib ([fela](https://github.com/rofrischmann/fela)) on my project, and I have to pass the className directly to your component, that doesn't allow it :/
This PR fixes that by concatenating any eventual className passed by the user to the wrapper.
=> Allow user to pass className to headroom wrapper

.travis.yml, src/index.js
This commit introduces a new prop: `calcHeightOnResize`. When this prop
has the value `true`, the Headroom component will add a resize listener
and recalculate the height of the wrapping div on resize.
Fixes https://github.com/KyleAMathews/react-headroom/issues/100
=> Add option to recalculate height on resize

src/index.js
`calcHeightOnResize` is omitted to avoid unknown prop warnings:
```
Uncaught (node:9556) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Warning: Exception thrown by hook while handling onBeforeMountComponent: E
rror: Warning: Unknown prop `calcHeightOnResize` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
in div (created by Headroom)
in div (created by Headroom)
```
=> Omitting prop when rendering

.npmignore
The current version of react-headroom (2.2.1) has this folder in its structure and should not be installed through npm :
The purpose of this directory is to provide a demo, so I guess nobody will run it through their node_modules/ directory.
=> fix: prevent www/ directory from publish to npm

package.json
Since version 0.2.2 shallowequal size went from 3.4kB to 561B. 
Also fixes #148
=> bump shallowequal

src/index.js, src/shouldUpdate.js, test/calc.js
A fix for issue #154 where the menu flashes in when scrolling past the height of the menu.
This is done by adding a boolean for animation in state, and adding an additional state in shouldUpdate that is triggered if you scroll past the height and pinstart and the state is unfixed.
=> Avoid flash of animation when scrolling from top

package.json, src/index.js
Fixes #167 
Replaced `componentWillReceiveProps` lifecycle method with `getDerivedStateFromProps ` and `componentDidUpdate`. This is a breaking change as `getDerivedStateFromProps` was added in react 16.3.0. I updated package.json peerDependencies to reflect that.
=> migrate from componentWillReceiveProps

src/index.js
Prevents an error that occurs if the parent no longer exists on `componentWillUnmount`
=> Check that parent exists when unmounting

src/index.js, src/supportsPassiveEvents.js
Added support for passive event listeners to improve scroll performance. 
This PR is pretty much based of @undirectlookable's [PR](https://github.com/KyleAMathews/react-headroom/pull/165).
I thought it might be a good addition and the previous PR went spooky quiet, thus I opened this one. 
The feature detection util function is taken from MDN. 
Reference: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#Improving_scrolling_performance_with_passive_listeners 
P.S.:
1. wow, I just realized that all those changes actually are all taken from other source... hahah 😆 
2. I noticed a `window.removeEventListener` call in `componentWillUnmount` lifecycle. I was wondering why it's there, since there's no other place where there's `window.addEventListener`. The only …
=> feat: support passive event listeners

src/index.js
The header doesn't stay at the top of the page when scrolling to the top of the page quickly with Safari on MacOS.
https://github.com/KyleAMathews/react-headroom/issues/185
Delay `unfixed` state change with `setTimeout()`.
Glitches are not happening anymore, although the header still disappears for a few milliseconds when scrolling to the top quickly.
=> Fix: Delay unfix state change to prevent Safari glitch
